Repository codestates-seb/seb40_main_024, pull requests merged in 2022-12, with the labels that each got.

#234 [BE] fix: 쿼리 order by 수정 / ceiling 으로 수정
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: [BE]

#235 refactor : MemberDelete 일부 구현됩니다.
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/entity/Member.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#236 [FE] 페이지네이션 재구현, name 유효성검사 자릿수수정, 테스트코드삭제
  front/package-lock.json
  front/package.json
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardCommentPost.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Component/Board/Pagination.css
  front/src/Component/Board/Pagination.js
  front/src/Component/Member/LoginBox.js
  front/src/Component/Member/SignupBox.js
  front/src/Pages/Asset/Exchange.js
Labels: [FE]

#239 refactor : MemberDelete 완전 구현완료.
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#241 [BE] fix: 리버트의 리버트..
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#243 refactor : MemberDelete 테스트
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
Labels: [BE]

#244 [FE] 회원관련 API header 추가, 모달 재수정
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardCommentPost.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Member/MyInfo.js
  front/src/Pages/Board/FreeBoard.js
Labels: [FE]

#246 [BE] feat: Board & Comment -> POST, UPDATE, DELETE 로그인 사용자
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
Labels: [BE]

#248 [BE] feat: Goal -> 로그인된 사용자 확인 적용
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: [BE]

#250 [FE] 게시물View추가, 게시글 ( 작성,수정,삭제) 코멘트 ( 작성,수정,삭제 ) 토큰값 헤더 추가, 비로그인시 버튼 모달안내 추가
  front/src/App.js
  front/src/Component/Board/AllBoardList.js
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Component/Common/NavebarRev.js
  front/src/Pages/Board/Board.js
  front/src/Pages/Board/BoardPage.js
  front/src/Pages/Board/FreeBoardPage.js
  front/src/Pages/Board/ModifyBoard.js
Labels: [FE]

#252 [FE] 비로그인시 게시물열람 불가능 및 모달 추가, 아이디값 동일하지 않을경우 수정 삭제 안보이게 구현, 모달 z-index수정
  front/src/Component/Board/AllBoardList.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Common/Modal.js
Labels: [FE]

#254 [BE] feat: asset 로그인 구현
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/dto/AssetEditDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/entity/AssetEditor.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
Labels: [BE]

#255 [BE] fix: 목표자산 PATCH 관련
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: [BE]

#256 [BE] fix: asset post 500에러 처리
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
Labels: Bug, [BE]

#258 [FE] 게시물 post or patch 양식안맞게 보낼 시 안내문구 추가, 작성 삭제 수정 완료안내문구 추가, 코멘트부분 로그인검증 추가, 회원탈퇴 안내문구 추가
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardCommentPost.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/NavebarRev.js
  front/src/Component/Member/LoginBox.js
  front/src/Component/Member/MyInfo.js
  front/src/Component/Member/SignupBox.js
  front/src/Pages/Board/Board.js
  front/src/Pages/Board/BoardPage.js
  front/src/Pages/Board/ModifyBoard.js
Labels: [FE]

#259 [BE] fix: 성학님 커밋 이후 빌드실패 픽스
  server/src/main/java/com/codestates/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#260 [BE] fix: asset get one 500에러 처리
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
Labels: [BE]

#262 [FE] 회원탈퇴 관련 모달버그 수정, 좋아요 클릭시 중복 방지 추가
  front/src/Component/Board/BoardContents.js
  front/src/Component/Member/MyInfo.js
Labels: [FE]

#263 [FE] 목표 자산 axios 헤더 추가, 금액 오류 처리
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#265 [FE] 회원정보수정 키입력시 반복get요청 버그 수정 및 모달인풋 위치변경
  front/src/Component/Board/BoardContents.js
  front/src/Component/Member/MyInfo.js
Labels: [FE]

#268 [FE] Delete: 불필요한 파일 제거
  front/src/App.js
  front/src/Pages/Asset/Exchange.js
  front/src/Pages/Board/ShareBoard.js
Labels: [FE]

#274 [Main] Update
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Board/AllBoardList.js
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardCommentPost.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Component/Common/NavebarRev.js
  front/src/Component/Member/LoginBox.js
  front/src/Component/Member/MyInfo.js
  front/src/Component/Member/SignupBox.js
  front/src/Pages/Asset/AssetChange.js
  front/src/Pages/Asset/AssetChangeTest.js
  front/src/Pages/Asset/AssetChangettt.js
  front/src/Pages/Asset/AssetTargetTest.js
  front/src/Pages/Asset/Exchange.js
  front/src/Pages/Board/Board.js
  front/src/Pages/Board/BoardPage.js
  front/src/Pages/Board/FreeBoardPage.js
  front/src/Pages/Board/ModifyBoard.js
  front/src/Pages/Board/ShareBoard.js
  front/src/Redux/store.js
  front/src/Redux/titleSlice.js
  front/src/index.js
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/dto/AssetEditDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/entity/AssetEditor.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
  server/src/main/java/com/codestates/server/auth/MemberDetailsService.java
  server/src/main/java/com/codestates/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/dto/BoardLikedByDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/entity/BoardLikedBy.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepositoryLikedBy.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [FE], [BE]

#275 [BE] origin 설정
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
Labels: [BE]

#277 [FE] 코드정리
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#278 ec2 주소 최종
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
Labels: [BE]

#279 EC2 주소 변경
  front/public/favicon.ico
  front/public/favicon1.ico
  front/public/index.html
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Pages/Asset/AssetChange.js
  front/src/Pages/Asset/AssetChangeTest.js
  front/src/Pages/Asset/AssetTargetTest.js
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
Labels: [BE]

#284 배포 준비
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
Labels: [BE]

#286 [FE] 머지 전 정리
  front/src/Pages/Asset/AssetTargetPage.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#289 [BE] fix: token time
  server/src/main/resources/application-mysql.yml
  server/src/main/resources/application.yml
Labels: [BE]

#290 feat: 로그인시 홈화면 버튼 알맞게 구현
  front/src/Component/Common/Button.js
  front/src/Component/Home/MainMiddle.js
Labels: [FE]

#293 [FE] 목표 모달 추가, 안내문구 추가
  README.md
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Common/Button.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#299 [FE] 목표 모달 수정
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Component/Home/Img/Asset.jpg
  front/src/Component/Home/Img/Asset.png
  front/src/Component/Home/MainImgData.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#300 [Main] 배포 후 버그수정 3
  README.md
  front/src/App.js
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Component/Home/Img/Asset.jpg
  front/src/Component/Home/Img/Asset.png
  front/src/Component/Home/MainImgData.js
  front/src/Pages/Asset/AssetChange.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]
