Repository codestates-seb/seb40_main_024, pull requests merged in 2022-11, with the labels that each got.

#15 [BE] feat: 라이브러리 및 리소스 추가.
  server/build.gradle
  server/src/main/resources/application-mysql.yml
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: documentation

#16 test : commit test 커밋경로 확인 및 (@EnableJpaAuditing 어노테이션 추가)
  server/build.gradle
  server/src/main/java/com/codestates/server/ServerApplication.java
Labels: documentation

#17 feat: h2경로 재설정 및 데이터소스 추가.(주석 표시 참고해주세요)
  server/src/main/resources/application.yml
Labels: documentation

#21 [FE] feat: 페이지 기본 틀 구현
  front/package-lock.json
  front/src/Component/BoardContents.js
  front/src/Component/Comments.js
  front/src/Component/PayConfirm.js
  front/src/Component/Profile.js
  front/src/Component/ProfileIcon.js
  front/src/Component/Subscript.js
  front/src/Pages/BoardContentPage.js
  front/src/Pages/InfoPage.js
  front/src/Pages/MainHome.js
  front/src/Pages/MyPage.js
  front/src/Pages/PaymentConfirmPage.js
  front/src/Pages/PaymentPage.js
  front/src/Pages/SubscriptionPage.js
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/stub/BoardStub.java
Labels: FE

#26 feat: 멤버 엔티티 매핑하기 위한 자료.
  server/src/main/java/com/codestates/server/member/entity/Member.java
Labels: documentation

#27 feat: 멤버 엔티티 매핑하기 위한 자료.
  server/src/main/java/com/codestates/server/member/status/MemberStatus.java
Labels: documentation

#41 [BE] feat: asset crud 기본 구현
  server/src/main/generated/com/codestates/server/asset/mapper/AssetMapperImpl.java
  server/src/main/generated/com/codestates/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/codestates/server/comment/mapper/CommentMapperImpl.java
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
Labels: BE

#43 [BE] feat: 목표 자산 기능 구현, 게시판 좋아요 및 페이지 업데이트
  server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/board/stub/BoardStub.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/goal/mapper/GoalMapper.java
  server/src/main/java/com/codestates/server/goal/repository/GoalRepository.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: BE

#45 feat: 1차 코드 구현... 리팩토링 많이 필요로함....
  server/src/main/java/com/codestates/server/exception/CustomException.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/exception/ExceptionController.java
  server/src/main/java/com/codestates/server/exception/Response.java
  server/src/main/java/com/codestates/server/jwt/TokenProvider.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetails.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetailsService.java
  server/src/main/java/com/codestates/server/jwt/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/jwt/config/JwtSecurityConfig.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenDto.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenPostDto.java
  server/src/main/java/com/codestates/server/jwt/entity/Jwt.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/jwt/repository/JwtRepository.java
  server/src/main/java/com/codestates/server/member/dto/LoginDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/entity/Member.java
  server/src/main/java/com/codestates/server/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: BE

#54 [BE] fix: Asset patch 버그 수정
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
Labels: BE

#62 [BE] feat: Stub 업데이트
  server/src/main/java/com/codestates/server/board/stub/BoardStub.java
  server/src/main/java/com/codestates/server/comment/entity/Comment.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: BE

#69 feat : 거의 완성...
  server/build.gradle
  server/src/main/generated/com/codestates/server/asset/mapper/AssetMapperImpl.java
  server/src/main/generated/com/codestates/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/codestates/server/comment/mapper/CommentMapperImpl.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/exception/ExceptionController.java
  server/src/main/java/com/codestates/server/exception/Response.java
  server/src/main/java/com/codestates/server/jwt/TokenProvider.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetails.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetailsService.java
  server/src/main/java/com/codestates/server/jwt/config/JwtSecurityConfig.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenDto.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenPostDto.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/jwt/repository/JwtRepository.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/LoginDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/entity/Member.java
  server/src/main/java/com/codestates/server/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
  server/src/main/java/com/codestates/server/member/status/MemberStatus.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: BE

#71 feat : 로그인 구현 진짜 거의 완성...
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: BE

#73 [BE] fix: stub 랜덤 댓글 수정
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: BE

#74 [BE] feat: ngrok 통신을 위한 CORS 설정
  server/src/main/java/com/codestates/server/ServerApplication.java
  server/src/main/java/com/codestates/server/configuration/WebConfig.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: BE

#81 feat : CORS 코드 수정.
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: [BE]

#82 feat : CORS 코드 수정2
  server/src/main/java/com/codestates/server/configuration/WebConfig.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: [BE]

#86 [BE] fix: CORS setting
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: [BE]

#98 [FE] css 수정
  front/.env
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Asset/Progress_bar.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Common/Button.js
  front/src/Component/Member/MyInfo.js
  front/src/Component/Member/MyInfoUpdate.js
  front/src/Component/Member/Profile.js
  front/src/Component/Member/ProfileIcon.js
  front/src/Pages/Asset/AssetTargetPage.js
  front/src/Redux/CommentAPI.js
  front/src/Redux/store.js
  front/src/index.js
Labels: [FE]

#99 feat: navbar 리뉴얼 & 기존 navbar remove
  front/src/Component/Board/FreeBoardList.js
  front/src/Component/Common/Navbar.js
  front/src/Component/Common/NavebarRev.js
  front/src/Component/Home/MainMiddle.js
  front/src/Pages/Asset/Asset.js
  front/src/Pages/Asset/AssetChange.js
  front/src/Pages/Asset/AssetTargetPage.js
  front/src/Pages/Asset/AssetTargetTest.js
  front/src/Pages/Board/AssetBoardPage.js
  front/src/Pages/Board/BoardContentPage.js
  front/src/Pages/Board/FreeBoard.js
  front/src/Pages/Board/FreeBoardPage.js
  front/src/Pages/Board/ShareBoard.js
  front/src/Pages/Home/MainHome.js
  front/src/Pages/Member/ForgotPasswordPage.js
  front/src/Pages/Member/InfoPage.js
  front/src/Pages/Member/LoginPage.js
  front/src/Pages/Member/MyPage.js
  front/src/Pages/Member/SignupPage.js
  front/src/Redux/store.js
Labels: [FE]

#107 [FE]design: 회원정보 수정페이지 레이아웃 재설정
  front/src/Component/Asset/AssetSettingTest.js
  front/src/Component/Common/Button.js
  front/src/Component/Member/MyInfo.js
  front/src/Component/Member/MyInfoUpdate.js
Labels: [FE]

#109 [BE] feat: CORS 구현중 - get 오류 수정중
  server/src/main/java/com/codestates/server/auth/MemberDetailsService.java
  server/src/main/java/com/codestates/server/auth/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/com/codestates/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetails.java
  server/src/main/java/com/codestates/server/jwt/auth/CustomDetailsService.java
  server/src/main/java/com/codestates/server/jwt/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenDto.java
  server/src/main/java/com/codestates/server/jwt/dto/TokenPostDto.java
  server/src/main/java/com/codestates/server/jwt/entity/Jwt.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/codestates/server/jwt/repository/JwtRepository.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/LoginDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberListDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberRegisterDto.java
  server/src/main/java/com/codestates/server/member/entity/Member.java
  server/src/main/java/com/codestates/server/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: [BE]

#111 [BE] fix: Stub 랜덤 자산 X10 업데이트
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#116 [BE] fix: member GET 버그 수정
  server/src/main/java/com/codestates/server/auth/MemberDetailsService.java
  server/src/main/java/com/codestates/server/configuration/WebConfig.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#124 [FE] design: 자산&목표 현황 페이지 수정
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/NavebarRev.js
  front/src/Pages/Asset/AssetChange.js
  front/src/Pages/Asset/AssetTargetPage.js
Labels: [FE]

#125 [BE] fix: 게시물 삭제시 댓글 삭제 연동 / Board, Comment, Goal 500 에러 수정
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/repository/CommentRepository.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: [BE]

#127 refactor : memberRefactoring complete
  server/src/main/java/com/codestates/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/LoginDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberListDto.java
  server/src/main/java/com/codestates/server/member/dto/MemberRegisterDto.java
  server/src/main/java/com/codestates/server/member/entity/Member.java
  server/src/main/java/com/codestates/server/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/server/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#140 [BE] fix: 게시물 페이지정보 추가 / 전체 조회 추가
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/assembler/CommentAssembler.java
  server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
Labels: [BE]

#141 [FE] 게시글전체목록, 게시글상세조회, 게시글등록, 게시글삭제 구현
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/Component/Board/AllBoardList.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Quill.js
  front/src/Pages/Board/AssetBoardPage.js
  front/src/Pages/Board/BoardContentPage.js
  front/src/Pages/Board/FreeBoard.js
  front/src/Pages/Pay/PaymentPage.js
  front/src/index.js
Labels: [FE]

#142 feat : 게시글 작성을 위한 생성자 생성
  server/src/main/java/com/codestates/server/member/entity/Member.java
Labels: [BE]

#143 [BE] feat: stub 추가 / 게시글과 댓글 리스폰스에 작성자 정보 포함
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
  server/src/main/java/com/codestates/server/comment/entity/Comment.java
  server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#152 feat : Asset && Board 게시글 작성자 정보 조회 Dto @Setter 추가
  server/src/main/java/com/codestates/server/dto/LogoutDto.java
Labels: [BE]

#153 [BE] feat: 댓글 URI 변경 / 보드 검증 로직 추가 / 게시글, 댓글 리스폰스 수정
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
  server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
Labels: [BE]

#154 feat : Asset && Board 게시글 작성자 정보 조회 Dto @Setter 추가
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
Labels: [BE]

#156 [FE] 게시물 좋아요기능 구현 및 랜더링 에러 수정
  front/src/Component/Board/BoardContents.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Pages/Board/BoardContentPage.js
Labels: [FE]

#157 [BE] fix : asset +,- 부분 구현 완료
  server/src/main/generated/com/codestates/server/asset/mapper/AssetMapperImpl.java
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
  server/src/main/resources/application.yml
Labels: [BE]

#158 [FE] 전체 게시글 리스트 sort적용 및 네이밍 수정
  front/src/Component/Board/BoardFreeList.js
Labels: [FE]

#159 [BE] feat: asset +,- 구현 완료 최종
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
Labels: [BE]

#167 [BE] feat: 게시판 태그 추가 / exception 추가 / stub 랜덤 태그 배정
  server/build.gradle
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#171 [BE] feat: 게시글 태그별로 모아보기 / PATCH 시 게시글 tag 옵셔널로 변경
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
Labels: [BE]

#173 [BE] feat: asset entity 멤버 생성자 추가
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
Labels: [BE]

#174 [BE] feat: asset stub - 멤버 랜덤 배정
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#175 [BE] refactor: board status (ordinal -> string), link href fix / Goal 랜덤 자산 15개 stub 추가
  server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#176 [BE] feat: 목표 자산 PATCH 로직 변경 / targetLength 검증
  server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/goal/mapper/GoalMapper.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#179 refactor : MemberService erifyExistsEmail 에러코드 수정
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#180 [BE] feat: GOAL -> 멤버별 조회 추가, 엔드포인트 변경, 중복코드 제거
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
  server/src/main/java/com/codestates/server/goal/entity/Goal.java
  server/src/main/java/com/codestates/server/goal/repository/GoalRepository.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
Labels: [BE]

#189 feat : addExposedHeader(제발...) 추가
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
Labels: [BE]

#195 [BE] feat: assetType 명칭 수정 & member Id 값 추가
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_024.iml
  .idea/vcs.xml
  server/src/main/java/com/codestates/server/asset/controller/AssetController.java
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/entity/Asset.java
  server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
  server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
Labels: [BE]

#197 [BE] fix: 목표자산, 댓글, 좋아요 관련 refactor 및 fix
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/controller/CommentController.java
  server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
  server/src/main/java/com/codestates/server/comment/service/CommentService.java
  server/src/main/java/com/codestates/server/exception/ErrorResponse.java
  server/src/main/java/com/codestates/server/goal/controller/GoalController.java
  server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
  server/src/main/java/com/codestates/server/goal/mapper/GoalMapper.java
  server/src/main/java/com/codestates/server/goal/service/GoalService.java
  server/src/main/java/com/codestates/server/validator/NotSpace.java
  server/src/main/java/com/codestates/server/validator/NotSpaceValidator.java
Labels: [BE]

#200 feat : refreshToken 강제주입 및 필터 리팩토링
  server/src/main/java/com/codestates/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#201 [BE] fix: Board controller 간소화, like 예외처리 등
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
Labels: [BE]

#202 [BE] fix: post시 memberId 값 추가
  .idea/uiDesigner.xml
  server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
  server/src/main/java/com/codestates/server/asset/service/AssetService.java
Labels: [BE]

#203 [BE] feat: 쿼리 변경, 게시글 조회수 기능, 테스트 멤버 로그인 기능
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/comment/repository/CommentRepository.java
  server/src/main/java/com/codestates/server/goal/repository/GoalRepository.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#208 [FE] 토큰 디코드, 회원정보관련 API추가 및 페이지 통합, 404페이지 안내문구 수정
  front/src/App.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/NavebarRev.js
  front/src/Component/Member/MyInfo.js
  front/src/Component/Member/MyInfoUpdate.js
  front/src/Pages/ErrorPage/Error.js
  front/src/Pages/Member/InfoPage.js
  front/src/store/AuthContext.js
Labels: [FE]

#212 [BE] fix: Board mapper 정리 / 리드미 업데이트 외
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_024.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  README.md
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
Labels: [BE]

#214 [FE] 목표 통신 구현, 모달창 추가
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Component/Common/NavebarRev.js
  front/src/Pages/Asset/AssetTargetPage.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#215 [FE] 게시물 댓글 조회,수정,삭제,추가 부분 재구현
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardCommentPost.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Common/Button.js
  front/src/Pages/Board/BoardContentPage.js
Labels: [FE]

#216 [FE] 홈화면 이미지, 댓글창 수정
  front/src/Component/Board/BoardComment.js
  front/src/Component/Home/Img/Asset2.jpg
  front/src/Component/Home/Img/MainA.jpg
  front/src/Component/Home/Img/community.png
  front/src/Component/Home/MainImgData.js
  front/src/Component/Home/MainMiddle.js
Labels: [FE]

#218 [BE] refactor: 게시판 불필요 로직 제거 외
  server/build.gradle
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
Labels: [BE]

#222 [FE] feat: 목표 성취도 patch 구현
  front/src/Component/Asset/AssetList.js
  front/src/Component/Asset/AssetSetting.js
  front/src/Component/Asset/Asset_B_Data.js
  front/src/Component/Common/Button.js
  front/src/Component/Common/Modal.js
  front/src/Pages/Asset/AssetTargetTest.js
Labels: [FE]

#226 [BE] fix: tag renaming -> Category
  server/src/main/java/com/codestates/server/board/controller/BoardController.java
  server/src/main/java/com/codestates/server/board/dto/BoardDto.java
  server/src/main/java/com/codestates/server/board/entity/Board.java
  server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
  server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
  server/src/main/java/com/codestates/server/board/service/BoardService.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/stub/Stub.java
Labels: [BE]

#228 refactor : MemberUpdate 구현됩니다. (삭제는 곧 조치하겠습니다.)
  server/src/main/java/com/codestates/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/member/controller/MemberController.java
  server/src/main/java/com/codestates/server/member/dto/MemberDto.java
  server/src/main/java/com/codestates/server/member/service/MemberService.java
Labels: [BE]

#229 [BE] rename: 패키지 경로 변경으로 인한 수정
  server/src/main/java/com/codestates/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/auth/utils/ErrorResponder.java
Labels: [BE]

#230 [Fe] 태그-> 카테고리 네이밍 수정, 오픈api 테스트코드 추가
  front/src/App.js
  front/src/Component/Board/AllBoardList.js
  front/src/Component/Board/BoardComment.js
  front/src/Component/Board/BoardComments.js
  front/src/Component/Board/BoardContents.js
  front/src/Component/Board/BoardFreeList.js
  front/src/Component/Home/MainMiddle.js
  front/src/Pages/Asset/Exchange.js
  front/src/Pages/Board/FreeBoard.js
Labels: [FE]
